### ISSUE TITLE
Main page after login for admins and experimenters

### ISSUE THREAD

**Issue by mlfreer** [jrhorn424/recruiter#12]
![screen shot 2014-03-03 at 12 16 43 am](https://f.cloud.github.com/assets/5439311/2306727/14898f9e-a293-11e3-98b7-78cf4818b6cd.png)

_easy page just to go to other pages_

# NEW

add the link to the **Experimenters** which is visible only for admins
possibly we will need to add the experimenters to drop-down list for the admins
# again new

add the bottom line **manage account** as for users

**Comment by jrhorn424** [comment]
Have you seen the dashboard? The skeleton has been in place for a few weeks.

It's easier for you to track my progress if you break these down into what you want to see, and then prioritize those more-focused tasks.

**Comment by mlfreer** [comment]
ok great! it's done!

**Comment by mlfreer** [comment]
i've found the dashboard

**Comment by mlfreer** [comment]
so we can close this ticket?

**Comment by jrhorn424** [comment]
It's done for now. Links need to be fleshed out, but I think we'll do that as we complete the other parts of the system. Thanks for the reminder to close it!
