### ISSUE TITLE
Experiments page

### ISSUE THREAD

**Issue by mlfreer** [jrhorn424/recruiter#13]
![screen shot 2014-03-03 at 12 30 52 am](https://f.cloud.github.com/assets/5439311/2306756/0878de06-a295-11e3-86c3-52d1cb117d19.png)

about flags:
do it in a fastest way (in terms of development): if it is necessary to add also button like refresh to update the list according to the flag value.

button: edit experiment can be realized as in ORSEE like a link at the name of experiments

button **create experiment** can also be realized as link

**Comment by jrhorn424** [comment]
Closed by #26
