### ISSUE TITLE
Create Experiment

### ISSUE THREAD

**Issue by mlfreer** [jrhorn424/recruiter#14]
_visible for experimenters and admins_

![screen shot 2014-03-03 at 12 37 59 am](https://f.cloud.github.com/assets/5439311/2306775/1a6a23f8-a296-11e3-9a53-76b138a300ed.png)

Save will lead to the migration:
create_experiment with the mentioned attributes and add the experiment and experimenters to the join table

button **experiments** work as a link in the drop-down list and send the user to the experiments page

**do you need sql script here**?

**Comment by jrhorn424** [comment]
Closed by #26
