### ISSUE TITLE
Experiment page (description of the experiment)

### ISSUE THREAD

**Issue by mlfreer** [jrhorn424/recruiter#15]
![screen shot 2014-03-03 at 12 54 12 am](https://f.cloud.github.com/assets/5439311/2306817/4cbcfec8-a298-11e3-9b97-fffa6373c2a4.png)

**sorry where should be separate link to the session page and to the edit session page**

!! **assigned subjects** and **registered subjects** should be the links to the assigned subjects and registered subjects page !!

**Comment by jrhorn424** [comment]
Closed by #26
