### ISSUE TITLE
Create Session page

### ISSUE THREAD

**Issue by mlfreer** [jrhorn424/recruiter#17]
![screen shot 2014-03-05 at 3 55 31 pm](https://f.cloud.github.com/assets/5439311/2338398/9deb4bf8-a4a8-11e3-9f74-81f7aa4ec9e3.png)

the form is made also ok in ORSEE, so we can use the same template + the **active_for_registration** flag

**Comment by jrhorn424** [comment]
Please don't close issues until code has been reviewed inside a pull request.

**Comment by jrhorn424** [comment]
Closed by #26
