### ISSUE TITLE
Models_correction

### ISSUE THREAD

**Issue by mlfreer** [jrhorn424/recruiter#21]
In the db diagram: all the users have profile: it is wrong

**ONLY Subjects** have profiles

Still need to add:

Blacklist column on **Subject**
Active column on **Subject**
# add to experimenter:
- fisrt_name
- last_name

**Comment by jrhorn424** [comment]
Thanks for this. I'll make the association change.

As you'll notice, Experimenter inherits from User, so it already has the attributes you've requested.

**Comment by mlfreer** [comment]
great! thanks! but we still need to add for subjects the attributes which are mentioned

**Comment by jrhorn424** [comment]
@PaulPodolsky is there any crossover here with any tickets you're working on? I thought I saw this mentioned elsewhere.

**Comment by ppodolsky** [comment]
I've only added has_one profile to users.rb, it was neccesary for profile contoller.

**Comment by mlfreer** [comment]
and the same is about this one: should we close it? or it is necessary firstly to merge Paul's code?  if so i can reassign it to @PaulPodolsky ??
