### ISSUE TITLE
Experimenter_page

### ISSUE THREAD

**Issue by mlfreer** [jrhorn424/recruiter#22]
Header and drop-down as usual:
in the main part:
list of all experimenters and admins in the format:
e-mail | first_name | last_name | type (experimenter or admin) | edit (button or link) |

under the table: buttons: 
- add new
- back (to the main page)

**Comment by jrhorn424** [comment]
This is only for admins, correct? If you like, you can take screenshots of the pages as they are if it makes it clearer what you want to link to.

**Comment by mlfreer** [comment]
yes, you're right
![screen shot 2014-03-12 at 6 27 15 am](https://f.cloud.github.com/assets/5439311/2393584/4414a064-a996-11e3-91ef-f0b6feee5685.png)

link to the page which is the first one after login
