### ISSUE TITLE
Add_or edit_experimenter_page

### ISSUE THREAD

**Issue by mlfreer** [jrhorn424/recruiter#23]
The standart header, footer, etc
and in the main part:
input form:
- e-mail (with the current one if exists)
- first_name (with the current one if exists)
- last_name (with the current one if exists)
- type ((with the current one if exists)

button: **add** (if it the the adding page)
            **save** (if it is the edit page)

action on the add page:
send the e-mail like confirmation for the user with the link to the personal cabinet with creating the password

**Comment by jrhorn424** [comment]
I'm sorry, but I don't understand:

> send the e-mail like confirmation for the user with the link to the personal cabinet with creating the password

**Comment by mlfreer** [comment]
e-mail like after signing button the **register**

Welcome to the ICES Recruiter!

You’ve signed up as experimenter
 “mfreer@masonlive.gmu.edu”.

If this was a mistake, no further action is necessary.

If you need to register you need to confirm your account:
*\* confirm your account *\* (in this case it will be also the creation of password)

**Comment by mlfreer** [comment]
an the link will connect to the page like 
http://ices-experiments.org/users/edit
but for experimenters: without **current password** and button is *\* create**
also there is no information about _unsubscribe_
