### ISSUE TITLE
Drop-down

### ISSUE THREAD

**Issue by mlfreer** [jrhorn424/recruiter#24]
Add to standard drop-down list (admins and experimenters): **manage account** (as for subjects)
and add to standard d-d list for admin: **experimenter**

_sorry it was my fault, i've lost it before_

**Comment by jrhorn424** [comment]
I don't understand. Do you mean the navigation menu drop-down in the nav bar? Would you please reword this requirement: 

>  manage account (as for subjects)
> and add to standard d-d list for admin: experimenter

**Comment by mlfreer** [comment]
![screen shot 2014-03-12 at 6 16 09 am](https://f.cloud.github.com/assets/5439311/2393530/b5966684-a994-11e3-827e-160677ece3e0.png)

_it is the new drop-down list_

**Comment by jrhorn424** [comment]
That's clear, thank you!

**Comment by jrhorn424** [comment]
That's already got a place in the sidebar on the dashboard (or at least, that's where it should go). I'd like to leave the dropdown for account management grabbing information. Under that criteria, experiments, participants and experimenters should not be there. I'm willing to discuss this further.

It's really annoying not having a staging server deployed easily. If I had that, I could just screenshot and send it your way. I'll work on getting that as-painless-as-possible.

Here's a tool you can use to [annotate screenshots](http://evernote.com/skitch/). It might be easier than drawing from scratch, I don't know.
