### ISSUE TITLE
Heroku deploy works, but application is still failing

### ISSUE THREAD

**Issue by jrhorn424** [jrhorn424/recruiter#32]
http://recruiter-staging.herokuapp.com/

Generating a 500 response. Possibly related to `delayed_job`. Will investigate.

**Comment by jrhorn424** [comment]
![errors_-_recruiter_-_new_relic](https://f.cloud.github.com/assets/388761/2489038/3a3ec678-b152-11e3-9a28-ebc65b20f2fa.png)

**Comment by ppodolsky** [comment]
http://rocky-reaches-2395.herokuapp.com/

**Comment by jrhorn424** [comment]
We already have a heroku instance at
ices-recruiter-staging.herokuapp.com for staging and I have an app
reserves for production as well. Did you get my message last week about
the fixes?

## 

Jeffrey Horn
jeff@jrhorn.me
http://hello.jrhorn.me/

**Comment by ppodolsky** [comment]
I will use this instance for release deployment (because I will be in need of using paid add-ons, probably). I will deploy to your staging area soon.

P.S. I've dealt with CONNECT grant by myself.

**Comment by ppodolsky** [comment]
> Generating a 500 response. Possibly related to delayed_job. Will investigate.

No. It is related to postgres adapter. I think, you should run db:migrate before you launch app:)

**Comment by jrhorn424** [comment]
> Could you grant me CONNECT privilege on heroku database? I won't be 
> able to deal with your app correctly without configuring of the 
> database in proper way.

I've confirmed that all you need is access to the heroku instance, which 
you should have had prior to May 4. Let me know if you need help getting 
started with heroku, but their docs are a great place to start. If 
you're trying to access the DB without using the toolchain, you can see: 
https://devcenter.heroku.com/articles/connecting-to-heroku-postgres-databases-from-outside-of-heroku.

**Comment by jrhorn424** [comment]
> I will use this instance for release deployment (because I will be in 
> need of using paid add-ons, probably). I will deploy to your staging 
> area soon.

If paid add-ons are needed, you can contact Stan Tsurilnikov at ICES to 
arrange for that. They'll probably want to transfer the instances to an 
ICES-controlled account.

If you look at the setup on the staging box, they all utilize the free 
tier for associated services. You can setup a cronjob on the box to fire 
every hour, which is a sneaky way to prevent your dyno from being 
shutdown.

**Comment by ppodolsky** [comment]
Thank you, it has been already done and working in a proper way
