### ISSUE TITLE
Session Check in Page

### ISSUE THREAD

**Issue by mlfreer** [jrhorn424/recruiter#33]
![img_20140321_195811_344](https://f.cloud.github.com/assets/5439311/2489196/3ec334fa-b156-11e3-9292-c1a2985d9b35.jpg)
- # is just the nuber in the table
- G# is the necessary and unique attribute for subject
- adding subject by G# also saving changes in the session. (if there is no subh G# in db, so just error message)
- shown_up and participated  are flags, 0 by default

**Comment by ppodolsky** [comment]
Would like to suggest splitting the issue into two ones: Check In Page and Payments.
Check In Page has been ended.

**Comment by jrhorn424** [comment]
I think that's an improvement. Our legacy recruiter conflated these functions as well.
