### ISSUE TITLE
Баги-баги

### ISSUE THREAD

**Issue by mlfreer** [jrhorn424/recruiter#47]
1) наш любимый:
![screen shot 2014-07-02 at 11 10 43 am](https://cloud.githubusercontent.com/assets/5439311/3453917/8d224ee6-01ca-11e4-8a5f-b67c7416ed17.png)
![screen shot 2014-07-02 at 11 10 38 am](https://cloud.githubusercontent.com/assets/5439311/3453918/8d38be92-01ca-11e4-9710-3cf073994877.png)

помним что субъект доступен для того чтобы be assigned if and only if active == 1 & профайл заполнен 

2) в 
![screen shot 2014-07-02 at 11 24 45 am](https://cloud.githubusercontent.com/assets/5439311/3453932/bbe56362-01ca-11e4-8088-dae49a220331.png)

добавить окно всплывающее которое позволило бы подредактировать дефолтный текст в последний момент (дефолтный текст мы задаем в settings а актуальный правим по ходу на вкус и цвет менеджера)

3)
![screen shot 2014-07-02 at 11 25 55 am](https://cloud.githubusercontent.com/assets/5439311/3453945/e5c37e26-01ca-11e4-984a-4815fcb99fc1.png)
- ты считаешь что как написано справа это красиво?
- можно сделать так чтобы я мог поменять статус без захождения в профиль, те тупо через правую херозу?

**Comment by ppodolsky** [comment]
> ты считаешь что как написано справа это красиво?

Честно - хз. Мне казалось, что более или менее нормально было, когда роль была в скобочках. Переместить направо - такое пожелание в прошлом ишшузе было. Справа я ее не хотел приделывать, да и не знаю как именно. Если конкретные идеи есть - то пиши
