### ISSUE TITLE
Add PaulPodolsky as a contributor to the project

### ISSUE THREAD

**Issue by mlfreer** [jrhorn424/recruiter#6]
He will the guy who'll help us in the case of emergency

**Comment by mlfreer** [comment]
And you said that will send me the server configuration and access passwords, i still didn't get it

**Comment by jrhorn424** [comment]
I've added that as a separate issue and assigned it to myself. Friday I setup continuous integration at semaphore, and once I hook in the deploy scripts, as soon as you push code to github it will be pushed to staging as long as the build doesn't fail.

I need Paul's github id. `PaulPodolsky` didn't work.

**Comment by mlfreer** [comment]
great!

**Comment by mlfreer** [comment]
https://github.com/PaulPodolsky
